### ASSIGNMENT 27th-November,2023
#### Study spliting method and stacking method in numpy.

#### 1. Splitting method: 
#### This involves splitting the array into divisions, which can be done by using the array name and the number of splits
#### (Equal divisions).

In [1]:
import numpy as np

In [5]:
A=np.arange(11)
print(A)


[ 0  1  2  3  4  5  6  7  8  9 10]


#### Splitting the array:
#### Example 1:

In [11]:
np.array_split(A,2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [12]:
np.array_split(A,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

#### 2. Stacking method:
#### Stacking involves dividing arrays using rows and columns.
#### Example 1:

In [6]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
result = np.concatenate((array1, array2), axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]]


### 3. Fancy Indexing: 
#### This allows for more complex and flexible indexing compared to simple integer or slice indexing.
#### Fancy indexing is of two types;
#### (a)Integer Array indexing:
#### Integer array indexing uses integers as indices to acess elements in other array.
#### Example:

In [6]:
import numpy as np
first_array=np.arange(3,6)
print(first_array)

[3 4 5]


In [7]:
indices=np.array([0,2])
second_array=first_array[indices]
print(second_array)

[3 5]


#### Modification:

In [8]:
first_array[indices]=0
print(first_array)

[0 4 0]


#### (b) Boolean Array Indexing:
#### This array indexing creates a condition for selecting elements in an array.
#### Example:

In [10]:
new_array=np.arange(5,20)
print(new_array)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [13]:
condition=new_array>15
next_array=new_array[condition]
print(next_array)

[16 17 18 19]


### 4. Masking:
#### Masking refers to the use of boolean arrays to index elements in an array based on certain conditions.
#### This method determines if a conditon is true or not

In [16]:
Array=np.array([10,3,30,7,50])
mask=Array%2==0
print(mask)

[ True False  True False  True]


In [15]:
#Printing this condition this way, gives only the elements that are true.
Array=np.array([10,3,30,7,50])
mask=Array%2==0
print(Array[mask]) 

[10 30 50]


#### Modification:

In [19]:
Array=np.array([10,3,30,27,50,3])
mask=(Array%2==0)|(Array%3==0)
print(Array[mask]) 

[10  3 30 27 50  3]
